# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ScillaMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScillaMobile
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'

  target 'ScillaMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ScillaMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScillaMobile-tvOS

  target 'ScillaMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
