// flow-typed signature: e8ca2749849615c7ce1b0f61be293cda
// flow-typed version: <<STUB>>/color_v3.1.2/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'color/index' {
  declare module.exports: $Exports<'color'>;
}
declare module 'color/index.js' {
  declare module.exports: $Exports<'color'>;
}
