// flow-typed signature: e713b539b74cad3d2457d812938022ec
// flow-typed version: <<STUB>>/react-native-step-indicator_v0.0.9/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-step-indicator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-step-indicator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-step-indicator/StepIndicator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-step-indicator/StepIndicator.js' {
  declare module.exports: $Exports<'react-native-step-indicator/StepIndicator'>;
}
