// flow-typed signature: d458a26a5bba3524bbf8921453366b8f
// flow-typed version: <<STUB>>/react-native-gesture-handler_v1.6.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-gesture-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-gesture-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-gesture-handler/__mocks__/RNGestureHandlerModule' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/createHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/createNativeWrapper' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/Directions' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/DrawerLayout' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureButtons' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureComponents' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureComponents.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandlerButton' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandlerButton.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandlerPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/gestureHandlerRootHOC' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandlerRootView.android.expo' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandlerRootView.android' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandlerRootView' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/Gestures' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/jestSetup' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/NativeViewGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/PlatformConstants' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/PlatformConstants.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/RNGestureHandlerModule' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/RNGestureHandlerModule.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/State' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/Swipeable' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/touchables/GenericTouchable' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/touchables/index' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/touchables/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/touchables/TouchableNativeFeedback.android' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/touchables/TouchableNativeFeedback' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/touchables/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/touchables/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/constants' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/DiscreteGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/DraggingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/Errors' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/FlingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/GestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/IndiscreteGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/LongPressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/NativeViewGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/NodeManager' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/PanGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/PinchGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/PressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/RotationGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/TapGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/web/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-gesture-handler/__mocks__/RNGestureHandlerModule.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/__mocks__/RNGestureHandlerModule'>;
}
declare module 'react-native-gesture-handler/createHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/createHandler'>;
}
declare module 'react-native-gesture-handler/createNativeWrapper.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/createNativeWrapper'>;
}
declare module 'react-native-gesture-handler/Directions.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/Directions'>;
}
declare module 'react-native-gesture-handler/DrawerLayout.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/DrawerLayout'>;
}
declare module 'react-native-gesture-handler/GestureButtons.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureButtons'>;
}
declare module 'react-native-gesture-handler/GestureComponents.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureComponents'>;
}
declare module 'react-native-gesture-handler/GestureComponents.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureComponents.web'>;
}
declare module 'react-native-gesture-handler/GestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandler'>;
}
declare module 'react-native-gesture-handler/GestureHandlerButton.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandlerButton'>;
}
declare module 'react-native-gesture-handler/GestureHandlerButton.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandlerButton.web'>;
}
declare module 'react-native-gesture-handler/GestureHandlerPropTypes.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandlerPropTypes'>;
}
declare module 'react-native-gesture-handler/gestureHandlerRootHOC.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/gestureHandlerRootHOC'>;
}
declare module 'react-native-gesture-handler/GestureHandlerRootView.android.expo.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandlerRootView.android.expo'>;
}
declare module 'react-native-gesture-handler/GestureHandlerRootView.android.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandlerRootView.android'>;
}
declare module 'react-native-gesture-handler/GestureHandlerRootView.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandlerRootView'>;
}
declare module 'react-native-gesture-handler/Gestures.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/Gestures'>;
}
declare module 'react-native-gesture-handler/index' {
  declare module.exports: $Exports<'react-native-gesture-handler'>;
}
declare module 'react-native-gesture-handler/index.js' {
  declare module.exports: $Exports<'react-native-gesture-handler'>;
}
declare module 'react-native-gesture-handler/jestSetup.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/jestSetup'>;
}
declare module 'react-native-gesture-handler/NativeViewGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/NativeViewGestureHandler'>;
}
declare module 'react-native-gesture-handler/PlatformConstants.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/PlatformConstants'>;
}
declare module 'react-native-gesture-handler/PlatformConstants.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/PlatformConstants.web'>;
}
declare module 'react-native-gesture-handler/RNGestureHandlerModule.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/RNGestureHandlerModule'>;
}
declare module 'react-native-gesture-handler/RNGestureHandlerModule.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/RNGestureHandlerModule.web'>;
}
declare module 'react-native-gesture-handler/State.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/State'>;
}
declare module 'react-native-gesture-handler/Swipeable.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/Swipeable'>;
}
declare module 'react-native-gesture-handler/touchables/GenericTouchable.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/touchables/GenericTouchable'>;
}
declare module 'react-native-gesture-handler/touchables/index.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/touchables/index'>;
}
declare module 'react-native-gesture-handler/touchables/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/touchables/TouchableHighlight'>;
}
declare module 'react-native-gesture-handler/touchables/TouchableNativeFeedback.android.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/touchables/TouchableNativeFeedback.android'>;
}
declare module 'react-native-gesture-handler/touchables/TouchableNativeFeedback.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/touchables/TouchableNativeFeedback'>;
}
declare module 'react-native-gesture-handler/touchables/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/touchables/TouchableOpacity'>;
}
declare module 'react-native-gesture-handler/touchables/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/touchables/TouchableWithoutFeedback'>;
}
declare module 'react-native-gesture-handler/web/constants.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/constants'>;
}
declare module 'react-native-gesture-handler/web/DiscreteGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/DiscreteGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/DraggingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/DraggingGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/Errors.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/Errors'>;
}
declare module 'react-native-gesture-handler/web/FlingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/FlingGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/GestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/GestureHandler'>;
}
declare module 'react-native-gesture-handler/web/IndiscreteGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/IndiscreteGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/LongPressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/LongPressGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/NativeViewGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/NativeViewGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/NodeManager.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/NodeManager'>;
}
declare module 'react-native-gesture-handler/web/PanGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/PanGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/PinchGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/PinchGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/PressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/PressGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/RotationGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/RotationGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/TapGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/TapGestureHandler'>;
}
declare module 'react-native-gesture-handler/web/utils.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/web/utils'>;
}
