// flow-typed signature: cfa73f263b6844254246c98f18a00ed3
// flow-typed version: <<STUB>>/react-automata_v4.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-automata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-automata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-automata/dist/react-automata.es' {
  declare module.exports: any;
}

declare module 'react-automata/dist/react-automata' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-automata/dist/react-automata.es.js' {
  declare module.exports: $Exports<'react-automata/dist/react-automata.es'>;
}
declare module 'react-automata/dist/react-automata.js' {
  declare module.exports: $Exports<'react-automata/dist/react-automata'>;
}
