// flow-typed signature: e4ca2bddc77bcf7fbc3f5c4f871380dd
// flow-typed version: <<STUB>>/react-native-firebase_v4.3.8/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-firebase/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/AdMobComponent' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/AdRequest' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/Banner' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/EventTypes' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/Interstitial' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/NativeExpress' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/RewardedVideo' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/admob/VideoOptions' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/analytics/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/phone/ConfirmationResult' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/phone/PhoneAuthListener' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/providers/EmailAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/providers/FacebookAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/providers/GithubAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/providers/GoogleAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/providers/OAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/providers/PhoneAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/providers/TwitterAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/auth/User' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/config/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/core/app' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/core/firebase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/crash/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/crashlytics/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/database/DataSnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/database/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/database/OnDisconnect' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/database/Query' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/database/Reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/database/transaction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/Blob' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/CollectionReference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/DocumentChange' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/DocumentReference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/DocumentSnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/FieldPath' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/FieldValue' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/GeoPoint' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/Path' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/Query' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/QuerySnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/Transaction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/TransactionHandler' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/utils/serialize' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/firestore/WriteBatch' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/functions/HttpsError' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/functions/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/functions/types.flow' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/iid/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/invites/AndroidInvitation' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/invites/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/invites/Invitation' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/invites/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/AnalyticsParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/AndroidParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/DynamicLink' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/IOSParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/ITunesParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/NavigationParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/SocialParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/links/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/messaging/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/messaging/RemoteMessage' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/messaging/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/AndroidAction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/AndroidChannel' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/AndroidChannelGroup' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/AndroidNotification' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/AndroidNotifications' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/AndroidRemoteInput' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/IOSNotification' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/Notification' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/notifications/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/perf/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/perf/Trace' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/storage/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/storage/reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/storage/task' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/modules/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/types/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/apps' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/Base64' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/emitter/EmitterSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/emitter/EventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/emitter/EventSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/emitter/EventSubscriptionVendor' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/events' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/internals' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/log' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/ModuleBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/native' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/ReferenceBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/utils/SyncTree' {
  declare module.exports: any;
}

declare module 'react-native-firebase/dist/version' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/AdMobComponent' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/AdRequest' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/Banner' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/EventTypes' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/Interstitial' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/NativeExpress' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/RewardedVideo' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/admob/VideoOptions' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/analytics/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/phone/ConfirmationResult' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/phone/PhoneAuthListener' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/EmailAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/FacebookAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/GithubAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/GoogleAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/OAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/PhoneAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/providers/TwitterAuthProvider' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/auth/User' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/config/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/core/app' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/core/firebase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/crash/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/crashlytics/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/DataSnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/OnDisconnect' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/Query' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/Reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/database/transaction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/Blob' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/CollectionReference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/DocumentChange' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/DocumentReference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/DocumentSnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/FieldPath' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/FieldValue' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/GeoPoint' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/Path' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/Query' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/QuerySnapshot' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/Transaction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/TransactionHandler' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/utils/serialize' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/firestore/WriteBatch' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/functions/HttpsError' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/functions/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/functions/types.flow' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/iid/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/invites/AndroidInvitation' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/invites/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/invites/Invitation' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/invites/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/AnalyticsParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/AndroidParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/DynamicLink' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/IOSParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/ITunesParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/NavigationParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/SocialParameters' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/links/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/messaging/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/messaging/RemoteMessage' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/messaging/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/AndroidAction' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/AndroidChannel' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/AndroidChannelGroup' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/AndroidNotification' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/AndroidNotifications' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/AndroidRemoteInput' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/IOSNotification' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/Notification' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/notifications/types' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/perf/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/perf/Trace' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/reference' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/storage/task' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/modules/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/types/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/apps' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/Base64' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EmitterSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventEmitter' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventSubscription' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/events' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/internals' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/log' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/ModuleBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/native' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/ReferenceBase' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/utils/SyncTree' {
  declare module.exports: any;
}

declare module 'react-native-firebase/lib/version' {
  declare module.exports: any;
}

declare module 'react-native-firebase/prettier.config' {
  declare module.exports: any;
}

declare module 'react-native-firebase/scripts/rnpm-postlink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-firebase/dist/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/index'>;
}
declare module 'react-native-firebase/dist/modules/admob/AdMobComponent.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/AdMobComponent'>;
}
declare module 'react-native-firebase/dist/modules/admob/AdRequest.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/AdRequest'>;
}
declare module 'react-native-firebase/dist/modules/admob/Banner.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/Banner'>;
}
declare module 'react-native-firebase/dist/modules/admob/EventTypes.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/EventTypes'>;
}
declare module 'react-native-firebase/dist/modules/admob/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/index'>;
}
declare module 'react-native-firebase/dist/modules/admob/Interstitial.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/Interstitial'>;
}
declare module 'react-native-firebase/dist/modules/admob/NativeExpress.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/NativeExpress'>;
}
declare module 'react-native-firebase/dist/modules/admob/RewardedVideo.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/RewardedVideo'>;
}
declare module 'react-native-firebase/dist/modules/admob/VideoOptions.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/admob/VideoOptions'>;
}
declare module 'react-native-firebase/dist/modules/analytics/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/analytics/index'>;
}
declare module 'react-native-firebase/dist/modules/auth/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/index'>;
}
declare module 'react-native-firebase/dist/modules/auth/phone/ConfirmationResult.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/phone/ConfirmationResult'>;
}
declare module 'react-native-firebase/dist/modules/auth/phone/PhoneAuthListener.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/phone/PhoneAuthListener'>;
}
declare module 'react-native-firebase/dist/modules/auth/providers/EmailAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/providers/EmailAuthProvider'>;
}
declare module 'react-native-firebase/dist/modules/auth/providers/FacebookAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/providers/FacebookAuthProvider'>;
}
declare module 'react-native-firebase/dist/modules/auth/providers/GithubAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/providers/GithubAuthProvider'>;
}
declare module 'react-native-firebase/dist/modules/auth/providers/GoogleAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/providers/GoogleAuthProvider'>;
}
declare module 'react-native-firebase/dist/modules/auth/providers/OAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/providers/OAuthProvider'>;
}
declare module 'react-native-firebase/dist/modules/auth/providers/PhoneAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/providers/PhoneAuthProvider'>;
}
declare module 'react-native-firebase/dist/modules/auth/providers/TwitterAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/providers/TwitterAuthProvider'>;
}
declare module 'react-native-firebase/dist/modules/auth/types.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/types'>;
}
declare module 'react-native-firebase/dist/modules/auth/User.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/auth/User'>;
}
declare module 'react-native-firebase/dist/modules/config/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/config/index'>;
}
declare module 'react-native-firebase/dist/modules/core/app.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/core/app'>;
}
declare module 'react-native-firebase/dist/modules/core/firebase.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/core/firebase'>;
}
declare module 'react-native-firebase/dist/modules/crash/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/crash/index'>;
}
declare module 'react-native-firebase/dist/modules/crashlytics/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/crashlytics/index'>;
}
declare module 'react-native-firebase/dist/modules/database/DataSnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/database/DataSnapshot'>;
}
declare module 'react-native-firebase/dist/modules/database/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/database/index'>;
}
declare module 'react-native-firebase/dist/modules/database/OnDisconnect.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/database/OnDisconnect'>;
}
declare module 'react-native-firebase/dist/modules/database/Query.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/database/Query'>;
}
declare module 'react-native-firebase/dist/modules/database/Reference.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/database/Reference'>;
}
declare module 'react-native-firebase/dist/modules/database/transaction.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/database/transaction'>;
}
declare module 'react-native-firebase/dist/modules/firestore/Blob.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/Blob'>;
}
declare module 'react-native-firebase/dist/modules/firestore/CollectionReference.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/CollectionReference'>;
}
declare module 'react-native-firebase/dist/modules/firestore/DocumentChange.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/DocumentChange'>;
}
declare module 'react-native-firebase/dist/modules/firestore/DocumentReference.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/DocumentReference'>;
}
declare module 'react-native-firebase/dist/modules/firestore/DocumentSnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/DocumentSnapshot'>;
}
declare module 'react-native-firebase/dist/modules/firestore/FieldPath.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/FieldPath'>;
}
declare module 'react-native-firebase/dist/modules/firestore/FieldValue.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/FieldValue'>;
}
declare module 'react-native-firebase/dist/modules/firestore/GeoPoint.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/GeoPoint'>;
}
declare module 'react-native-firebase/dist/modules/firestore/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/index'>;
}
declare module 'react-native-firebase/dist/modules/firestore/Path.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/Path'>;
}
declare module 'react-native-firebase/dist/modules/firestore/Query.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/Query'>;
}
declare module 'react-native-firebase/dist/modules/firestore/QuerySnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/QuerySnapshot'>;
}
declare module 'react-native-firebase/dist/modules/firestore/Transaction.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/Transaction'>;
}
declare module 'react-native-firebase/dist/modules/firestore/TransactionHandler.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/TransactionHandler'>;
}
declare module 'react-native-firebase/dist/modules/firestore/types.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/types'>;
}
declare module 'react-native-firebase/dist/modules/firestore/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/utils/index'>;
}
declare module 'react-native-firebase/dist/modules/firestore/utils/serialize.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/utils/serialize'>;
}
declare module 'react-native-firebase/dist/modules/firestore/WriteBatch.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/firestore/WriteBatch'>;
}
declare module 'react-native-firebase/dist/modules/functions/HttpsError.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/functions/HttpsError'>;
}
declare module 'react-native-firebase/dist/modules/functions/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/functions/index'>;
}
declare module 'react-native-firebase/dist/modules/functions/types.flow.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/functions/types.flow'>;
}
declare module 'react-native-firebase/dist/modules/iid/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/iid/index'>;
}
declare module 'react-native-firebase/dist/modules/invites/AndroidInvitation.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/invites/AndroidInvitation'>;
}
declare module 'react-native-firebase/dist/modules/invites/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/invites/index'>;
}
declare module 'react-native-firebase/dist/modules/invites/Invitation.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/invites/Invitation'>;
}
declare module 'react-native-firebase/dist/modules/invites/types.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/invites/types'>;
}
declare module 'react-native-firebase/dist/modules/links/AnalyticsParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/AnalyticsParameters'>;
}
declare module 'react-native-firebase/dist/modules/links/AndroidParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/AndroidParameters'>;
}
declare module 'react-native-firebase/dist/modules/links/DynamicLink.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/DynamicLink'>;
}
declare module 'react-native-firebase/dist/modules/links/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/index'>;
}
declare module 'react-native-firebase/dist/modules/links/IOSParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/IOSParameters'>;
}
declare module 'react-native-firebase/dist/modules/links/ITunesParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/ITunesParameters'>;
}
declare module 'react-native-firebase/dist/modules/links/NavigationParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/NavigationParameters'>;
}
declare module 'react-native-firebase/dist/modules/links/SocialParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/SocialParameters'>;
}
declare module 'react-native-firebase/dist/modules/links/types.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/links/types'>;
}
declare module 'react-native-firebase/dist/modules/messaging/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/messaging/index'>;
}
declare module 'react-native-firebase/dist/modules/messaging/RemoteMessage.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/messaging/RemoteMessage'>;
}
declare module 'react-native-firebase/dist/modules/messaging/types.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/messaging/types'>;
}
declare module 'react-native-firebase/dist/modules/notifications/AndroidAction.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/AndroidAction'>;
}
declare module 'react-native-firebase/dist/modules/notifications/AndroidChannel.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/AndroidChannel'>;
}
declare module 'react-native-firebase/dist/modules/notifications/AndroidChannelGroup.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/AndroidChannelGroup'>;
}
declare module 'react-native-firebase/dist/modules/notifications/AndroidNotification.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/AndroidNotification'>;
}
declare module 'react-native-firebase/dist/modules/notifications/AndroidNotifications.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/AndroidNotifications'>;
}
declare module 'react-native-firebase/dist/modules/notifications/AndroidRemoteInput.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/AndroidRemoteInput'>;
}
declare module 'react-native-firebase/dist/modules/notifications/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/index'>;
}
declare module 'react-native-firebase/dist/modules/notifications/IOSNotification.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/IOSNotification'>;
}
declare module 'react-native-firebase/dist/modules/notifications/Notification.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/Notification'>;
}
declare module 'react-native-firebase/dist/modules/notifications/types.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/notifications/types'>;
}
declare module 'react-native-firebase/dist/modules/perf/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/perf/index'>;
}
declare module 'react-native-firebase/dist/modules/perf/Trace.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/perf/Trace'>;
}
declare module 'react-native-firebase/dist/modules/storage/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/storage/index'>;
}
declare module 'react-native-firebase/dist/modules/storage/reference.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/storage/reference'>;
}
declare module 'react-native-firebase/dist/modules/storage/task.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/storage/task'>;
}
declare module 'react-native-firebase/dist/modules/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/modules/utils/index'>;
}
declare module 'react-native-firebase/dist/types/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/types/index'>;
}
declare module 'react-native-firebase/dist/utils/apps.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/apps'>;
}
declare module 'react-native-firebase/dist/utils/Base64.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/Base64'>;
}
declare module 'react-native-firebase/dist/utils/emitter/EmitterSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/emitter/EmitterSubscription'>;
}
declare module 'react-native-firebase/dist/utils/emitter/EventEmitter.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/emitter/EventEmitter'>;
}
declare module 'react-native-firebase/dist/utils/emitter/EventSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/emitter/EventSubscription'>;
}
declare module 'react-native-firebase/dist/utils/emitter/EventSubscriptionVendor.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/emitter/EventSubscriptionVendor'>;
}
declare module 'react-native-firebase/dist/utils/events.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/events'>;
}
declare module 'react-native-firebase/dist/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/index'>;
}
declare module 'react-native-firebase/dist/utils/internals.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/internals'>;
}
declare module 'react-native-firebase/dist/utils/log.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/log'>;
}
declare module 'react-native-firebase/dist/utils/ModuleBase.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/ModuleBase'>;
}
declare module 'react-native-firebase/dist/utils/native.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/native'>;
}
declare module 'react-native-firebase/dist/utils/ReferenceBase.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/ReferenceBase'>;
}
declare module 'react-native-firebase/dist/utils/SyncTree.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/utils/SyncTree'>;
}
declare module 'react-native-firebase/dist/version.js' {
  declare module.exports: $Exports<'react-native-firebase/dist/version'>;
}
declare module 'react-native-firebase/lib/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/index'>;
}
declare module 'react-native-firebase/lib/modules/admob/AdMobComponent.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/AdMobComponent'>;
}
declare module 'react-native-firebase/lib/modules/admob/AdRequest.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/AdRequest'>;
}
declare module 'react-native-firebase/lib/modules/admob/Banner.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/Banner'>;
}
declare module 'react-native-firebase/lib/modules/admob/EventTypes.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/EventTypes'>;
}
declare module 'react-native-firebase/lib/modules/admob/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/index'>;
}
declare module 'react-native-firebase/lib/modules/admob/Interstitial.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/Interstitial'>;
}
declare module 'react-native-firebase/lib/modules/admob/NativeExpress.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/NativeExpress'>;
}
declare module 'react-native-firebase/lib/modules/admob/RewardedVideo.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/RewardedVideo'>;
}
declare module 'react-native-firebase/lib/modules/admob/VideoOptions.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/admob/VideoOptions'>;
}
declare module 'react-native-firebase/lib/modules/analytics/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/analytics/index'>;
}
declare module 'react-native-firebase/lib/modules/auth/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/index'>;
}
declare module 'react-native-firebase/lib/modules/auth/phone/ConfirmationResult.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/phone/ConfirmationResult'>;
}
declare module 'react-native-firebase/lib/modules/auth/phone/PhoneAuthListener.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/phone/PhoneAuthListener'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/EmailAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/EmailAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/FacebookAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/FacebookAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/GithubAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/GithubAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/GoogleAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/GoogleAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/OAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/OAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/PhoneAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/PhoneAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/providers/TwitterAuthProvider.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/providers/TwitterAuthProvider'>;
}
declare module 'react-native-firebase/lib/modules/auth/types.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/types'>;
}
declare module 'react-native-firebase/lib/modules/auth/User.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/auth/User'>;
}
declare module 'react-native-firebase/lib/modules/config/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/config/index'>;
}
declare module 'react-native-firebase/lib/modules/core/app.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/core/app'>;
}
declare module 'react-native-firebase/lib/modules/core/firebase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/core/firebase'>;
}
declare module 'react-native-firebase/lib/modules/crash/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/crash/index'>;
}
declare module 'react-native-firebase/lib/modules/crashlytics/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/crashlytics/index'>;
}
declare module 'react-native-firebase/lib/modules/database/DataSnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/DataSnapshot'>;
}
declare module 'react-native-firebase/lib/modules/database/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/index'>;
}
declare module 'react-native-firebase/lib/modules/database/OnDisconnect.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/OnDisconnect'>;
}
declare module 'react-native-firebase/lib/modules/database/Query.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/Query'>;
}
declare module 'react-native-firebase/lib/modules/database/Reference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/Reference'>;
}
declare module 'react-native-firebase/lib/modules/database/transaction.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/database/transaction'>;
}
declare module 'react-native-firebase/lib/modules/firestore/Blob.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/Blob'>;
}
declare module 'react-native-firebase/lib/modules/firestore/CollectionReference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/CollectionReference'>;
}
declare module 'react-native-firebase/lib/modules/firestore/DocumentChange.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/DocumentChange'>;
}
declare module 'react-native-firebase/lib/modules/firestore/DocumentReference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/DocumentReference'>;
}
declare module 'react-native-firebase/lib/modules/firestore/DocumentSnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/DocumentSnapshot'>;
}
declare module 'react-native-firebase/lib/modules/firestore/FieldPath.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/FieldPath'>;
}
declare module 'react-native-firebase/lib/modules/firestore/FieldValue.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/FieldValue'>;
}
declare module 'react-native-firebase/lib/modules/firestore/GeoPoint.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/GeoPoint'>;
}
declare module 'react-native-firebase/lib/modules/firestore/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/index'>;
}
declare module 'react-native-firebase/lib/modules/firestore/Path.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/Path'>;
}
declare module 'react-native-firebase/lib/modules/firestore/Query.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/Query'>;
}
declare module 'react-native-firebase/lib/modules/firestore/QuerySnapshot.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/QuerySnapshot'>;
}
declare module 'react-native-firebase/lib/modules/firestore/Transaction.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/Transaction'>;
}
declare module 'react-native-firebase/lib/modules/firestore/TransactionHandler.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/TransactionHandler'>;
}
declare module 'react-native-firebase/lib/modules/firestore/types.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/types'>;
}
declare module 'react-native-firebase/lib/modules/firestore/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/utils/index'>;
}
declare module 'react-native-firebase/lib/modules/firestore/utils/serialize.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/utils/serialize'>;
}
declare module 'react-native-firebase/lib/modules/firestore/WriteBatch.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/firestore/WriteBatch'>;
}
declare module 'react-native-firebase/lib/modules/functions/HttpsError.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/functions/HttpsError'>;
}
declare module 'react-native-firebase/lib/modules/functions/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/functions/index'>;
}
declare module 'react-native-firebase/lib/modules/functions/types.flow.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/functions/types.flow'>;
}
declare module 'react-native-firebase/lib/modules/iid/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/iid/index'>;
}
declare module 'react-native-firebase/lib/modules/invites/AndroidInvitation.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/invites/AndroidInvitation'>;
}
declare module 'react-native-firebase/lib/modules/invites/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/invites/index'>;
}
declare module 'react-native-firebase/lib/modules/invites/Invitation.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/invites/Invitation'>;
}
declare module 'react-native-firebase/lib/modules/invites/types.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/invites/types'>;
}
declare module 'react-native-firebase/lib/modules/links/AnalyticsParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/AnalyticsParameters'>;
}
declare module 'react-native-firebase/lib/modules/links/AndroidParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/AndroidParameters'>;
}
declare module 'react-native-firebase/lib/modules/links/DynamicLink.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/DynamicLink'>;
}
declare module 'react-native-firebase/lib/modules/links/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/index'>;
}
declare module 'react-native-firebase/lib/modules/links/IOSParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/IOSParameters'>;
}
declare module 'react-native-firebase/lib/modules/links/ITunesParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/ITunesParameters'>;
}
declare module 'react-native-firebase/lib/modules/links/NavigationParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/NavigationParameters'>;
}
declare module 'react-native-firebase/lib/modules/links/SocialParameters.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/SocialParameters'>;
}
declare module 'react-native-firebase/lib/modules/links/types.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/links/types'>;
}
declare module 'react-native-firebase/lib/modules/messaging/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/messaging/index'>;
}
declare module 'react-native-firebase/lib/modules/messaging/RemoteMessage.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/messaging/RemoteMessage'>;
}
declare module 'react-native-firebase/lib/modules/messaging/types.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/messaging/types'>;
}
declare module 'react-native-firebase/lib/modules/notifications/AndroidAction.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/AndroidAction'>;
}
declare module 'react-native-firebase/lib/modules/notifications/AndroidChannel.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/AndroidChannel'>;
}
declare module 'react-native-firebase/lib/modules/notifications/AndroidChannelGroup.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/AndroidChannelGroup'>;
}
declare module 'react-native-firebase/lib/modules/notifications/AndroidNotification.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/AndroidNotification'>;
}
declare module 'react-native-firebase/lib/modules/notifications/AndroidNotifications.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/AndroidNotifications'>;
}
declare module 'react-native-firebase/lib/modules/notifications/AndroidRemoteInput.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/AndroidRemoteInput'>;
}
declare module 'react-native-firebase/lib/modules/notifications/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/index'>;
}
declare module 'react-native-firebase/lib/modules/notifications/IOSNotification.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/IOSNotification'>;
}
declare module 'react-native-firebase/lib/modules/notifications/Notification.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/Notification'>;
}
declare module 'react-native-firebase/lib/modules/notifications/types.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/notifications/types'>;
}
declare module 'react-native-firebase/lib/modules/perf/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/perf/index'>;
}
declare module 'react-native-firebase/lib/modules/perf/Trace.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/perf/Trace'>;
}
declare module 'react-native-firebase/lib/modules/storage/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/index'>;
}
declare module 'react-native-firebase/lib/modules/storage/reference.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/reference'>;
}
declare module 'react-native-firebase/lib/modules/storage/task.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/storage/task'>;
}
declare module 'react-native-firebase/lib/modules/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/modules/utils/index'>;
}
declare module 'react-native-firebase/lib/types/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/types/index'>;
}
declare module 'react-native-firebase/lib/utils/apps.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/apps'>;
}
declare module 'react-native-firebase/lib/utils/Base64.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/Base64'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EmitterSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EmitterSubscription'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventEmitter.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventEmitter'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventSubscription.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventSubscription'>;
}
declare module 'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/emitter/EventSubscriptionVendor'>;
}
declare module 'react-native-firebase/lib/utils/events.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/events'>;
}
declare module 'react-native-firebase/lib/utils/index.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/index'>;
}
declare module 'react-native-firebase/lib/utils/internals.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/internals'>;
}
declare module 'react-native-firebase/lib/utils/log.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/log'>;
}
declare module 'react-native-firebase/lib/utils/ModuleBase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/ModuleBase'>;
}
declare module 'react-native-firebase/lib/utils/native.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/native'>;
}
declare module 'react-native-firebase/lib/utils/ReferenceBase.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/ReferenceBase'>;
}
declare module 'react-native-firebase/lib/utils/SyncTree.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/utils/SyncTree'>;
}
declare module 'react-native-firebase/lib/version.js' {
  declare module.exports: $Exports<'react-native-firebase/lib/version'>;
}
declare module 'react-native-firebase/prettier.config.js' {
  declare module.exports: $Exports<'react-native-firebase/prettier.config'>;
}
declare module 'react-native-firebase/scripts/rnpm-postlink.js' {
  declare module.exports: $Exports<'react-native-firebase/scripts/rnpm-postlink'>;
}
