// flow-typed signature: a7b638bde3d16676ac04e7dba0e0457b
// flow-typed version: <<STUB>>/xdate_v0.8.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xdate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xdate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xdate/build/externs' {
  declare module.exports: any;
}

declare module 'xdate/src/extras' {
  declare module.exports: any;
}

declare module 'xdate/src/xdate' {
  declare module.exports: any;
}

declare module 'xdate/test/adding' {
  declare module.exports: any;
}

declare module 'xdate/test/constructors' {
  declare module.exports: any;
}

declare module 'xdate/test/diffing' {
  declare module.exports: any;
}

declare module 'xdate/test/formatting-extras' {
  declare module.exports: any;
}

declare module 'xdate/test/formatting' {
  declare module.exports: any;
}

declare module 'xdate/test/getters' {
  declare module.exports: any;
}

declare module 'xdate/test/old' {
  declare module.exports: any;
}

declare module 'xdate/test/parsing' {
  declare module.exports: any;
}

declare module 'xdate/test/setters' {
  declare module.exports: any;
}

declare module 'xdate/test/test' {
  declare module.exports: any;
}

declare module 'xdate/test/utc-mode' {
  declare module.exports: any;
}

declare module 'xdate/test/utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xdate/build/externs.js' {
  declare module.exports: $Exports<'xdate/build/externs'>;
}
declare module 'xdate/src/extras.js' {
  declare module.exports: $Exports<'xdate/src/extras'>;
}
declare module 'xdate/src/xdate.js' {
  declare module.exports: $Exports<'xdate/src/xdate'>;
}
declare module 'xdate/test/adding.js' {
  declare module.exports: $Exports<'xdate/test/adding'>;
}
declare module 'xdate/test/constructors.js' {
  declare module.exports: $Exports<'xdate/test/constructors'>;
}
declare module 'xdate/test/diffing.js' {
  declare module.exports: $Exports<'xdate/test/diffing'>;
}
declare module 'xdate/test/formatting-extras.js' {
  declare module.exports: $Exports<'xdate/test/formatting-extras'>;
}
declare module 'xdate/test/formatting.js' {
  declare module.exports: $Exports<'xdate/test/formatting'>;
}
declare module 'xdate/test/getters.js' {
  declare module.exports: $Exports<'xdate/test/getters'>;
}
declare module 'xdate/test/old.js' {
  declare module.exports: $Exports<'xdate/test/old'>;
}
declare module 'xdate/test/parsing.js' {
  declare module.exports: $Exports<'xdate/test/parsing'>;
}
declare module 'xdate/test/setters.js' {
  declare module.exports: $Exports<'xdate/test/setters'>;
}
declare module 'xdate/test/test.js' {
  declare module.exports: $Exports<'xdate/test/test'>;
}
declare module 'xdate/test/utc-mode.js' {
  declare module.exports: $Exports<'xdate/test/utc-mode'>;
}
declare module 'xdate/test/utilities.js' {
  declare module.exports: $Exports<'xdate/test/utilities'>;
}
