// flow-typed signature: d4efb80ea80147135c5370b3a026124f
// flow-typed version: <<STUB>>/xstate_v3.3.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xstate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xstate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xstate/dist/xstate.graph' {
  declare module.exports: any;
}

declare module 'xstate/dist/xstate' {
  declare module.exports: any;
}

declare module 'xstate/dist/xstate.utils' {
  declare module.exports: any;
}

declare module 'xstate/es/actions' {
  declare module.exports: any;
}

declare module 'xstate/es/constants' {
  declare module.exports: any;
}

declare module 'xstate/es/graph' {
  declare module.exports: any;
}

declare module 'xstate/es/index' {
  declare module.exports: any;
}

declare module 'xstate/es/Machine' {
  declare module.exports: any;
}

declare module 'xstate/es/mapState' {
  declare module.exports: any;
}

declare module 'xstate/es/matchesState' {
  declare module.exports: any;
}

declare module 'xstate/es/patterns' {
  declare module.exports: any;
}

declare module 'xstate/es/scxml' {
  declare module.exports: any;
}

declare module 'xstate/es/State' {
  declare module.exports: any;
}

declare module 'xstate/es/StateNode' {
  declare module.exports: any;
}

declare module 'xstate/es/types' {
  declare module.exports: any;
}

declare module 'xstate/es/utils' {
  declare module.exports: any;
}

declare module 'xstate/lib/actions' {
  declare module.exports: any;
}

declare module 'xstate/lib/constants' {
  declare module.exports: any;
}

declare module 'xstate/lib/graph' {
  declare module.exports: any;
}

declare module 'xstate/lib/history' {
  declare module.exports: any;
}

declare module 'xstate/lib/index' {
  declare module.exports: any;
}

declare module 'xstate/lib/Machine' {
  declare module.exports: any;
}

declare module 'xstate/lib/mapState' {
  declare module.exports: any;
}

declare module 'xstate/lib/matchesState' {
  declare module.exports: any;
}

declare module 'xstate/lib/patterns' {
  declare module.exports: any;
}

declare module 'xstate/lib/scxml' {
  declare module.exports: any;
}

declare module 'xstate/lib/State' {
  declare module.exports: any;
}

declare module 'xstate/lib/StateNode' {
  declare module.exports: any;
}

declare module 'xstate/lib/types' {
  declare module.exports: any;
}

declare module 'xstate/lib/utils' {
  declare module.exports: any;
}

declare module 'xstate/webpack.config' {
  declare module.exports: any;
}

declare module 'xstate/webpack.utils.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xstate/dist/xstate.graph.js' {
  declare module.exports: $Exports<'xstate/dist/xstate.graph'>;
}
declare module 'xstate/dist/xstate.js' {
  declare module.exports: $Exports<'xstate/dist/xstate'>;
}
declare module 'xstate/dist/xstate.utils.js' {
  declare module.exports: $Exports<'xstate/dist/xstate.utils'>;
}
declare module 'xstate/es/actions.js' {
  declare module.exports: $Exports<'xstate/es/actions'>;
}
declare module 'xstate/es/constants.js' {
  declare module.exports: $Exports<'xstate/es/constants'>;
}
declare module 'xstate/es/graph.js' {
  declare module.exports: $Exports<'xstate/es/graph'>;
}
declare module 'xstate/es/index.js' {
  declare module.exports: $Exports<'xstate/es/index'>;
}
declare module 'xstate/es/Machine.js' {
  declare module.exports: $Exports<'xstate/es/Machine'>;
}
declare module 'xstate/es/mapState.js' {
  declare module.exports: $Exports<'xstate/es/mapState'>;
}
declare module 'xstate/es/matchesState.js' {
  declare module.exports: $Exports<'xstate/es/matchesState'>;
}
declare module 'xstate/es/patterns.js' {
  declare module.exports: $Exports<'xstate/es/patterns'>;
}
declare module 'xstate/es/scxml.js' {
  declare module.exports: $Exports<'xstate/es/scxml'>;
}
declare module 'xstate/es/State.js' {
  declare module.exports: $Exports<'xstate/es/State'>;
}
declare module 'xstate/es/StateNode.js' {
  declare module.exports: $Exports<'xstate/es/StateNode'>;
}
declare module 'xstate/es/types.js' {
  declare module.exports: $Exports<'xstate/es/types'>;
}
declare module 'xstate/es/utils.js' {
  declare module.exports: $Exports<'xstate/es/utils'>;
}
declare module 'xstate/lib/actions.js' {
  declare module.exports: $Exports<'xstate/lib/actions'>;
}
declare module 'xstate/lib/constants.js' {
  declare module.exports: $Exports<'xstate/lib/constants'>;
}
declare module 'xstate/lib/graph.js' {
  declare module.exports: $Exports<'xstate/lib/graph'>;
}
declare module 'xstate/lib/history.js' {
  declare module.exports: $Exports<'xstate/lib/history'>;
}
declare module 'xstate/lib/index.js' {
  declare module.exports: $Exports<'xstate/lib/index'>;
}
declare module 'xstate/lib/Machine.js' {
  declare module.exports: $Exports<'xstate/lib/Machine'>;
}
declare module 'xstate/lib/mapState.js' {
  declare module.exports: $Exports<'xstate/lib/mapState'>;
}
declare module 'xstate/lib/matchesState.js' {
  declare module.exports: $Exports<'xstate/lib/matchesState'>;
}
declare module 'xstate/lib/patterns.js' {
  declare module.exports: $Exports<'xstate/lib/patterns'>;
}
declare module 'xstate/lib/scxml.js' {
  declare module.exports: $Exports<'xstate/lib/scxml'>;
}
declare module 'xstate/lib/State.js' {
  declare module.exports: $Exports<'xstate/lib/State'>;
}
declare module 'xstate/lib/StateNode.js' {
  declare module.exports: $Exports<'xstate/lib/StateNode'>;
}
declare module 'xstate/lib/types.js' {
  declare module.exports: $Exports<'xstate/lib/types'>;
}
declare module 'xstate/lib/utils.js' {
  declare module.exports: $Exports<'xstate/lib/utils'>;
}
declare module 'xstate/webpack.config.js' {
  declare module.exports: $Exports<'xstate/webpack.config'>;
}
declare module 'xstate/webpack.utils.config.js' {
  declare module.exports: $Exports<'xstate/webpack.utils.config'>;
}
