// flow-typed signature: 59e41cd964e6867459abedec18be726f
// flow-typed version: <<STUB>>/@react-native-firebase/analytics_v7.3.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-firebase/analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-firebase/analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-firebase/analytics/lib/index' {
  declare module.exports: any;
}

declare module '@react-native-firebase/analytics/lib/structs' {
  declare module.exports: any;
}

declare module '@react-native-firebase/analytics/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-firebase/analytics/lib/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/analytics/lib/index'>;
}
declare module '@react-native-firebase/analytics/lib/structs.js' {
  declare module.exports: $Exports<'@react-native-firebase/analytics/lib/structs'>;
}
declare module '@react-native-firebase/analytics/lib/version.js' {
  declare module.exports: $Exports<'@react-native-firebase/analytics/lib/version'>;
}
