// flow-typed signature: 86055407ed30343418a37c54e72514d9
// flow-typed version: <<STUB>>/@react-native-firebase/app_v7.3.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-firebase/app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-firebase/app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-firebase/app/lib/common/Base64' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/deeps' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/id' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/index' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/MutatableParams' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/path' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/promise' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/ReferenceBase' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/serialize' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/struct' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/common/validate' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/FirebaseApp' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/index' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/constants' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/FirebaseModule' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/index' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/NativeFirebaseError' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/registry/app' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/registry/namespace' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/registry/nativeModule' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/internal/SharedEventEmitter' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/utils/index' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/utils/UtilsStatics' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/lib/version' {
  declare module.exports: any;
}

declare module '@react-native-firebase/app/react-native.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-firebase/app/lib/common/Base64.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/Base64'>;
}
declare module '@react-native-firebase/app/lib/common/deeps.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/deeps'>;
}
declare module '@react-native-firebase/app/lib/common/id.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/id'>;
}
declare module '@react-native-firebase/app/lib/common/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/index'>;
}
declare module '@react-native-firebase/app/lib/common/MutatableParams.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/MutatableParams'>;
}
declare module '@react-native-firebase/app/lib/common/path.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/path'>;
}
declare module '@react-native-firebase/app/lib/common/promise.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/promise'>;
}
declare module '@react-native-firebase/app/lib/common/ReferenceBase.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/ReferenceBase'>;
}
declare module '@react-native-firebase/app/lib/common/serialize.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/serialize'>;
}
declare module '@react-native-firebase/app/lib/common/struct.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/struct'>;
}
declare module '@react-native-firebase/app/lib/common/validate.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/common/validate'>;
}
declare module '@react-native-firebase/app/lib/FirebaseApp.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/FirebaseApp'>;
}
declare module '@react-native-firebase/app/lib/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/index'>;
}
declare module '@react-native-firebase/app/lib/internal/constants.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/constants'>;
}
declare module '@react-native-firebase/app/lib/internal/FirebaseModule.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/FirebaseModule'>;
}
declare module '@react-native-firebase/app/lib/internal/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/index'>;
}
declare module '@react-native-firebase/app/lib/internal/NativeFirebaseError.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/NativeFirebaseError'>;
}
declare module '@react-native-firebase/app/lib/internal/registry/app.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/registry/app'>;
}
declare module '@react-native-firebase/app/lib/internal/registry/namespace.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/registry/namespace'>;
}
declare module '@react-native-firebase/app/lib/internal/registry/nativeModule.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/registry/nativeModule'>;
}
declare module '@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter'>;
}
declare module '@react-native-firebase/app/lib/internal/SharedEventEmitter.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/internal/SharedEventEmitter'>;
}
declare module '@react-native-firebase/app/lib/utils/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/utils/index'>;
}
declare module '@react-native-firebase/app/lib/utils/UtilsStatics.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/utils/UtilsStatics'>;
}
declare module '@react-native-firebase/app/lib/version.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/lib/version'>;
}
declare module '@react-native-firebase/app/react-native.config.js' {
  declare module.exports: $Exports<'@react-native-firebase/app/react-native.config'>;
}
